//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHA.Framework.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEachEntityTran
    {
        public string AccountName { get; set; }
        public string TransactionType { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<long> CurrentBalance { get; set; }
        public long IndividualID { get; set; }
    }
}
