//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDatabase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int TransID { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> TranstionTypeId { get; set; }
        public Nullable<int> ACnameID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TransDesc { get; set; }
    
        public virtual tblAccountName tblAccountName { get; set; }
        public virtual tblBank tblBank { get; set; }
        public virtual tblTransactionType tblTransactionType { get; set; }
    }
}
